### ISSUE TITLE
Can't get OpcNetDaAeServer.exe working

### ISSUE THREAD

**Issue by ayman-metwally-stream** [technosoftware-gmbh/opc-daae-server#8]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ y] I am running the latest version
- [ y] I checked the documentation and found no answer
- [ y] I checked to make sure that this issue has not already been filed
- [n] I am developing a client
- [ y] I am developing a server

# Expected Behavior

OPC clients should be able to see/start the running OPC DA server executable.

# Current Behavior

OPC clients can't "see" or start the OPC DA server.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

I've done the following:
1. Build the class library "ServerPlugin"

2. Add "ServerPlugin" dll as a reference to OpcNetDaAeServer project.
(I had to do this step since there was an issue on the referenced dll "serverplugin".

3. Now I have "OpcNetDaAeServer.exe" executable.
under ..\Server\ClassicSerer\net\Win32\Debug

4.  I ran the command "OpcNetDaAeServer.exe -regserver"
I tried both under normal user and Admin user
Note: the command doesn't return any message.

5. I ran "OpcNetDaAeServer.exe" 

6. I expected that this executable will run (and remain running) but nothing happens and my OPC client test tool is not seeing it (it can see Kepware and Matrikon).

## Context

* Operating System: Windows 10
* SDK version: 9.0.0.0

**Comment by technosoftware** [comment]
Issue not reproducible.

Used Environment
- Windows 10 64bit
- SDK: 10 (was used for development)
- OPC Core Components Redistributables: 3.00.108 (64bit Version)

If step 4 fails it should give an error. And step 5 is not required because if step 4 works the first client which connects to the server starts it.

It might also be that (D)COM security settings blocks the server, e.g. server ist started as Administrator but client under User.

**Comment by technosoftware** [comment]
Not an issue on code base
